name: Build and Deploy Script
on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Adding Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.0

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: ng build --base-href /nursing-houses/

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist/primebox/browser'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.4
        with:
          NG_APP_GOOGLE_MAPS_KEY: ${{ secrets.NG_APP_GOOGLE_MAPS_KEY }}
